services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Kompose FastAPI
      - APP_VERSION=1.0.0
      - APP_DESCRIPTION=My Awesome FastAPI Application
      - APP_ENV=development
      - DEBUG=true
      - API_PREFIX=/api/v1
    volumes:
      - ./src:/app/src